version: '3'

services:
  itau-auth:
    image: itau-challenge:latest
    command: ["java", "--spring.profiles.active=local", "-jar", "app.jar"]
    ports:
      - "9090:9090"
    volumes:
      - /etc/credentials:/etc/credentials
    environment:
      JWT_SIGNING_KEY: /etc/credentials/jwt-signing-key