server:
  servlet:
    context-path: /itau-challenge
  port: ${PORT:9090}

logging:
  config: classpath:log/logback.xml
  level:
    root: INFO
    spring: INFO
    app: INFO
    servlet: WARN
    web: WARN

application:
  token:
    aws-secret-signing-key-name: ${AWS_SECRET_KEY_NAME:jwt-itau-challenge}
    signing-key-name: ${JWT_SIGNING_KEY_NAME:/etc/credentials/jwt-signing-key}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s