server:
  servlet:
    context-path: /itau-challenge
  port: 9090

logging:
  config: classpath:log/logback.xml
  level:
    root: INFO
    spring: INFO
    app: INFO
    servlet: WARN
    web: WARN

application:
  token:
    aws-secret-signing-key-name: ${AWS_SECRET_KEY_NAME:jwt-itau-challenge}
    signing-key-name: ${JWT_SIGNING_KEY_NAME:/etc/credentials/jwt-signing-keya}