spring:
  application:
    name: itau-authentication

server:
  servlet:
    context-path: /itau-challenge
  port: 8080

logging:
  config: classpath:log/logback.xml
  level:
    root: INFO
    spring: INFO
    app: INFO
    servlet: WARN
    web: WARN

token:
  signing-key: {JWT_SIGNING_KEY}
